### PR TITLE
Kevin patch 1

### PR DESCRIPTION
**Pull request by lament29**
Create a file for storing and adding walls.

### CODE REVIEW

**Review by SadeenAlsabbagh — CHANGES_REQUESTED** [review]
Missing orientation for walls and implement the third variable z in the code block.

**Review by mahajan1806 — APPROVED** [review]
Looks good now.

**Review by mahajan1806 — APPROVED** [review]
Looks good!

**Review by SadeenAlsabbagh — APPROVED** [review]
Changes are made per request.

**Pull request merged**
