### PR TITLE
The functions of creat canvas and add is completed and tested.

### PR DESCRIPTION
**Pull request by Puyujiang**
This is a team work with both Abhishek and Prakhar

### CODE REVIEW

**Comment by REN-aissance** [comment]
Consider adding an exclusion for the .idea folder in .gitignore. I'm guessing it's related to IntelliJ IDEA. They appear to be workspace settings that should not be synced with git. Otherwise looks good!

**Comment by REN-aissance** [comment]
I realized I am able to make that adjustment to .gitignore

I recommend deleting the directories ".idea" and "out", as well as the file Sona-Drawing.iml if these are residue files, as I strongly suspect. If they are not residue, feel free to rollback my changes to .gitignore

**Comment by Puyujiang** [comment]
Thank you for your advise, I will look it up about the difference between IDEA and the workbench.

**Review by REN-aissance — APPROVED** [review]
Fixed conflicts with branch

**Comment by Puyujiang** [comment]
After changing it, the file no longer works on IDEA

**Comment by REN-aissance** [comment]
You need to keep those files that were deleted in order for it to work in your IDE, so just pulling won't work. I removed them from github and added an exclusion in .gitignore so they are not uploaded again, but those are your important IDE config files. I recommend cloning from before that pull and copy-pasting those config files where they were before. This time, they will not be uploaded to github due to the gitignore exclusion

**Pull request merged**
